-- Imported notes (docs/imported-notes-design-brief.md, 2026-09-16).
--
-- Rich Douglass's 61,773-person PAF export carried the notes he had
-- written on people over decades. The parser read every person-level
-- NOTE / SNOTE and the import dropped them on the floor: individuals has
-- no column for them, and Betsey's box (ancestor_notes) is the wrong
-- home — one row per user per person, carried across a refresh as the
-- reader's own words, owner-only. A file's notes are the opposite on
-- every count: several per person, regenerated by each new file (they
-- ride the old tree's cascade, so the refresh code needs nothing), and
-- part of the record, so companions on a shared tree read them.
--
-- RLS mirrors individuals in the consolidated single-SELECT shape of the
-- 2026-09-15 disk-IO migration. No length cap: a file is what it is.

create table public.individual_notes (
  id            uuid primary key default gen_random_uuid(),
  tree_id       uuid not null references public.trees (id) on delete cascade,
  user_id       uuid not null references auth.users (id) on delete cascade,
  individual_id uuid not null references public.individuals (id) on delete cascade,
  position      smallint not null default 0,   -- order in the file
  content       text not null
);

create index individual_notes_individual_idx on public.individual_notes (individual_id);
create index individual_notes_tree_id_idx on public.individual_notes (tree_id);
create index individual_notes_user_id_idx on public.individual_notes (user_id);

alter table public.individual_notes enable row level security;

create policy "Users select their own or shared individual notes" on public.individual_notes
  for select
  using (
    (select auth.uid()) = user_id
    or tree_id in (select member_tree_ids())
  );

create policy "Users insert their own individual notes" on public.individual_notes
  for insert
  with check ((select auth.uid()) = user_id and is_tree_owner(tree_id));

create policy "Users update their own individual notes" on public.individual_notes
  for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id and is_tree_owner(tree_id));

create policy "Users delete their own individual notes" on public.individual_notes
  for delete
  using ((select auth.uid()) = user_id);
